import type { BlogPost } from "./types";
import { MOCK_HUBS } from "./mockDeltaData";

const WP_BASE_URL = import.meta.env.VITE_WP_BASE_URL || "https://deltainc.gr";

export const MOCK_POSTS: BlogPost[] = [
  {
    id: 5587, slug: "neoi-pinakes-ekpaideftikon-2026-opsyd",
    url: `${WP_BASE_URL}/neoi-pinakes-ekpaideftikon-2026-opsyd/`,
    title: "Νέοι Πίνακες Εκπαιδευτικών 2026: Αναλυτικός Οδηγός για τα Δικαιολογητικά στο ΟΠΣΥΔ",
    excerpt: "Αναλυτικός οδηγός για τη διαδικασία και τα δικαιολογητικά του ΟΠΣΥΔ ενόψει των νέων πινάκων εκπαιδευτικών 2026.",
    contentHtml: "<p>Αναλυτικός οδηγός...</p>",
    featuredImage: { id: 101, url: "https://images.unsplash.com/photo-1694230155228-cdde50083573?w=800", alt: "ΟΠΣΥΔ εκπαιδευτικοί", width: 800, height: 600, mimeType: "image/jpeg" },
    author: { id: 5, name: "Delta Editorial Team", slug: "delta-editorial-team", bio: "", avatar: null },
    hub: MOCK_HUBS[0],
    categories: [{ id: 342, name: "ΟΠΣΥΔ", slug: "opsyd-proslipsis-anaplirwtwn", url: `${WP_BASE_URL}/category/opsyd-proslipsis-anaplirwtwn/` }],
    tags: [{ id: 33, name: "important", slug: "important", url: `${WP_BASE_URL}/tag/important/` }],
    publishedAt: "2026-04-15T16:46:00+02:00", updatedAt: "2026-04-15T16:46:00+02:00",
    readingTimeMinutes: 8, isFeatured: true, seo: null, relatedPosts: [],
  },
  {
    id: 5588, slug: "asep-3k-2026-odigos-aitisis",
    url: `${WP_BASE_URL}/asep-3k-2026-odigos-aitisis/`,
    title: "ΑΣΕΠ 3Κ/2026: Πλήρης Οδηγός Αίτησης — Δικαιολογητικά & Προθεσμίες",
    excerpt: "Ο αναλυτικός οδηγός για την αίτηση στην προκήρυξη 3Κ/2026 του ΑΣΕΠ. Όλες οι απαιτήσεις και τα βήματα της διαδικασίας.",
    contentHtml: "<p>Αναλυτικός οδηγός ΑΣΕΠ...</p>",
    featuredImage: { id: 102, url: "https://images.unsplash.com/photo-1759317700289-2f4be8f9b1db?w=800", alt: "ΑΣΕΠ αίτηση", width: 800, height: 600, mimeType: "image/jpeg" },
    author: { id: 5, name: "Delta Editorial Team", slug: "delta-editorial-team", bio: "", avatar: null },
    hub: MOCK_HUBS[1],
    categories: [{ id: 285, name: "ΑΣΕΠ", slug: "prokirykseis-asep-sox", url: `${WP_BASE_URL}/category/prokirykseis-asep-sox/` }],
    tags: [],
    publishedAt: "2026-04-12T10:00:00+02:00", updatedAt: "2026-04-12T10:00:00+02:00",
    readingTimeMinutes: 6, isFeatured: false, seo: null, relatedPosts: [],
  },
  {
    id: 5589, slug: "metaptyxiaka-2026-deka-dimofili-programmata",
    url: `${WP_BASE_URL}/metaptyxiaka-2026-deka-dimofili/`,
    title: "Μεταπτυχιακά 2026: Τα 10 Πιο Δημοφιλή Προγράμματα στην Ελλάδα",
    excerpt: "Ανακαλύψτε τα πιο περιζήτητα μεταπτυχιακά προγράμματα για το ακαδημαϊκό έτος 2026-2027, με στοιχεία για δίδακτρα, διάρκεια και αιτήσεις.",
    contentHtml: "<p>Αναλυτικά μεταπτυχιακά...</p>",
    featuredImage: { id: 103, url: "https://images.unsplash.com/photo-1775503059048-214026cce5cf?w=800", alt: "Μεταπτυχιακά", width: 800, height: 600, mimeType: "image/jpeg" },
    author: { id: 6, name: "Σύνταξη Delta", slug: "suntaxi-delta", bio: "", avatar: null },
    hub: MOCK_HUBS[2],
    categories: [{ id: 286, name: "Μεταπτυχιακά", slug: "metaptychiaka", url: `${WP_BASE_URL}/category/metaptychiaka/` }],
    tags: [],
    publishedAt: "2026-04-10T09:00:00+02:00", updatedAt: "2026-04-10T09:00:00+02:00",
    readingTimeMinutes: 10, isFeatured: false, seo: null, relatedPosts: [],
  },
  {
    id: 5590, slug: "pistopoiisi-pliroforiakis-ekpaideftikon-2026",
    url: `${WP_BASE_URL}/pistopoiisi-pliroforiakis-ekpaideftikon-2026/`,
    title: "Πιστοποίηση Πληροφορικής Εκπαιδευτικών 2026: Τι Αλλάζει & Πώς να Προετοιμαστείτε",
    excerpt: "Νέες απαιτήσεις πιστοποίησης για εκπαιδευτικούς ψηφιακών δεξιοτήτων. Πλήρης οδηγός προετοιμασίας.",
    contentHtml: "<p>Πιστοποιήσεις...</p>",
    featuredImage: { id: 104, url: "https://images.unsplash.com/photo-1655393001768-d946c97d6fd1?w=800", alt: "Πιστοποιήσεις", width: 800, height: 600, mimeType: "image/jpeg" },
    author: { id: 5, name: "Delta Editorial Team", slug: "delta-editorial-team", bio: "", avatar: null },
    hub: MOCK_HUBS[3],
    categories: [{ id: 15, name: "Πιστοποιήσεις", slug: "pistopoihseis", url: `${WP_BASE_URL}/category/pistopoihseis/` }],
    tags: [],
    publishedAt: "2026-04-08T11:30:00+02:00", updatedAt: "2026-04-08T11:30:00+02:00",
    readingTimeMinutes: 7, isFeatured: false, seo: null, relatedPosts: [],
  },
  {
    id: 5591, slug: "opsyd-ypovoli-dikaiologitikon-odigos",
    url: `${WP_BASE_URL}/opsyd-ypovoli-dikaiologitikon-odigos/`,
    title: "Υποβολή Δικαιολογητικών ΟΠΣΥΔ: Ο Πλήρης Βήμα-Βήμα Οδηγός",
    excerpt: "Πρακτικές οδηγίες για την υποβολή δικαιολογητικών στο ΟΠΣΥΔ. Τι χρειάζεστε και πώς να αποφύγετε λάθη.",
    contentHtml: "<p>Οδηγός υποβολής...</p>",
    featuredImage: { id: 105, url: "https://images.unsplash.com/photo-1762330918491-f4288a62adb8?w=800", alt: "ΟΠΣΥΔ υποβολή", width: 800, height: 600, mimeType: "image/jpeg" },
    author: { id: 5, name: "Delta Editorial Team", slug: "delta-editorial-team", bio: "", avatar: null },
    hub: MOCK_HUBS[0],
    categories: [{ id: 342, name: "ΟΠΣΥΔ", slug: "opsyd-proslipsis-anaplirwtwn", url: `${WP_BASE_URL}/category/opsyd-proslipsis-anaplirwtwn/` }],
    tags: [],
    publishedAt: "2026-04-05T14:00:00+02:00", updatedAt: "2026-04-05T14:00:00+02:00",
    readingTimeMinutes: 9, isFeatured: false, seo: null, relatedPosts: [],
  },
  {
    id: 5592, slug: "asep-2g-ekpaideftikoi-imeromhnies",
    url: `${WP_BASE_URL}/asep-2g-ekpaideftikoi-imeromhnies/`,
    title: "ΑΣΕΠ 2Γ Εκπαιδευτικοί: Ημερομηνίες Εξετάσεων & Δικαιολογητικά 2026",
    excerpt: "Αναλυτικές πληροφορίες για τις εξετάσεις ΑΣΕΠ κατηγορίας 2Γ για εκπαιδευτικούς — ημερομηνίες, ύλη και δικαιολογητικά.",
    contentHtml: "<p>Εξετάσεις ΑΣΕΠ 2Γ...</p>",
    featuredImage: { id: 106, url: "https://images.unsplash.com/photo-1764720573370-5008f1ccc9fa?w=800", alt: "ΑΣΕΠ εξετάσεις", width: 800, height: 600, mimeType: "image/jpeg" },
    author: { id: 5, name: "Delta Editorial Team", slug: "delta-editorial-team", bio: "", avatar: null },
    hub: MOCK_HUBS[1],
    categories: [{ id: 285, name: "ΑΣΕΠ", slug: "prokirykseis-asep-sox", url: `${WP_BASE_URL}/category/prokirykseis-asep-sox/` }],
    tags: [{ id: 33, name: "important", slug: "important", url: `${WP_BASE_URL}/tag/important/` }],
    publishedAt: "2026-04-02T09:00:00+02:00", updatedAt: "2026-04-02T09:00:00+02:00",
    readingTimeMinutes: 5, isFeatured: false, seo: null, relatedPosts: [],
  },
];
