import type { Program } from "./types";
import { MOCK_HUBS } from "./mockDeltaData";

const WP_BASE_URL = import.meta.env.VITE_WP_BASE_URL || "https://deltainc.gr";

export const MOCK_PROGRAMS: Program[] = [
  {
    id: 901, slug: "msc-dioikisi-ekpaideutikwn-monadas",
    url: `${WP_BASE_URL}/programs/msc-dioikisi-ekpaideutikwn-monadas/`,
    title: "ΜΔΕ Διοίκηση Εκπαιδευτικών Μονάδων",
    excerpt: "Μεταπτυχιακό πρόγραμμα ειδίκευσης στη διοίκηση εκπαιδευτικών ιδρυμάτων και οργανισμών.",
    contentHtml: "<p>Πλήρης περιγραφή...</p>",
    featuredImage: { id: 201, url: "https://images.unsplash.com/photo-1775503059048-214026cce5cf?w=800", alt: "Διοίκηση Εκπαίδευσης", width: 800, height: 600, mimeType: "image/jpeg" },
    summary: { level: "Master", category: "Εκπαίδευση", university: "ΕΚΠΑ", mode: "Υβριδικό", city: "Αθήνα", uniType: "Δημόσιο", tuition: "3500", duration: "18 μήνες", language: "Ελληνικά", deadline: "2026-07-30", format: "Υβριδικό" },
    taxonomies: {
      level: [{ id: 1, name: "Master", slug: "master", url: "" }],
      category: [{ id: 2, name: "Εκπαίδευση", slug: "education", url: "" }],
      university: [{ id: 3, name: "ΕΚΠΑ", slug: "ekpa", url: "" }],
      mode: [{ id: 4, name: "Υβριδικό", slug: "hybrid", url: "" }],
      city: [{ id: 5, name: "Αθήνα", slug: "athens", url: "" }],
      uniType: [{ id: 6, name: "Δημόσιο", slug: "public", url: "" }],
    },
    sections: { overview: "", curriculum: "", admissions: "", outcomes: "", faq: "" },
    hub: MOCK_HUBS[2], isFeatured: true,
    publishedAt: "2026-03-01T10:00:00+02:00", updatedAt: "2026-03-05T11:00:00+02:00", seo: null,
  },
  {
    id: 902, slug: "msc-pliroforiki-stin-ekpaidefsi",
    url: `${WP_BASE_URL}/programs/msc-pliroforiki-stin-ekpaidefsi/`,
    title: "ΜΔΕ Πληροφορική στην Εκπαίδευση",
    excerpt: "Εξειδίκευση στην αξιοποίηση τεχνολογιών πληροφορικής και επικοινωνίας στη διδασκαλία.",
    contentHtml: "<p>Πλήρης περιγραφή...</p>",
    featuredImage: { id: 202, url: "https://images.unsplash.com/photo-1655393001768-d946c97d6fd1?w=800", alt: "Πληροφορική Εκπαίδευση", width: 800, height: 600, mimeType: "image/jpeg" },
    summary: { level: "Master", category: "Πληροφορική", university: "ΑΠΘ", mode: "Εξ Αποστάσεως", city: "Θεσσαλονίκη", uniType: "Δημόσιο", tuition: "2800", duration: "12 μήνες", language: "Ελληνικά", deadline: "2026-08-15", format: "Online" },
    taxonomies: {
      level: [{ id: 1, name: "Master", slug: "master", url: "" }],
      category: [{ id: 7, name: "Πληροφορική", slug: "informatics", url: "" }],
      university: [{ id: 8, name: "ΑΠΘ", slug: "auth", url: "" }],
      mode: [{ id: 9, name: "Εξ Αποστάσεως", slug: "online", url: "" }],
      city: [{ id: 10, name: "Θεσσαλονίκη", slug: "thessaloniki", url: "" }],
      uniType: [{ id: 6, name: "Δημόσιο", slug: "public", url: "" }],
    },
    sections: { overview: "", curriculum: "", admissions: "", outcomes: "", faq: "" },
    hub: MOCK_HUBS[2], isFeatured: false,
    publishedAt: "2026-03-10T10:00:00+02:00", updatedAt: "2026-03-10T10:00:00+02:00", seo: null,
  },
  {
    id: 903, slug: "msc-eidiki-agogi",
    url: `${WP_BASE_URL}/programs/msc-eidiki-agogi/`,
    title: "ΜΔΕ Ειδική Αγωγή και Εκπαίδευση",
    excerpt: "Εξειδίκευση στην εκπαίδευση ατόμων με ειδικές εκπαιδευτικές ανάγκες.",
    contentHtml: "<p>Πλήρης περιγραφή...</p>",
    featuredImage: { id: 203, url: "https://images.unsplash.com/photo-1762438135827-428acc0e8941?w=800", alt: "Ειδική Αγωγή", width: 800, height: 600, mimeType: "image/jpeg" },
    summary: { level: "Master", category: "Εκπαίδευση", university: "Πανεπιστήμιο Αθηνών", mode: "Δια Ζώσης", city: "Αθήνα", uniType: "Δημόσιο", tuition: "3000", duration: "24 μήνες", language: "Ελληνικά", deadline: "2026-09-01", format: "In-person" },
    taxonomies: {
      level: [{ id: 1, name: "Master", slug: "master", url: "" }],
      category: [{ id: 2, name: "Εκπαίδευση", slug: "education", url: "" }],
      university: [{ id: 11, name: "Πανεπιστήμιο Αθηνών", slug: "uoa", url: "" }],
      mode: [{ id: 12, name: "Δια Ζώσης", slug: "in-person", url: "" }],
      city: [{ id: 5, name: "Αθήνα", slug: "athens", url: "" }],
      uniType: [{ id: 6, name: "Δημόσιο", slug: "public", url: "" }],
    },
    sections: { overview: "", curriculum: "", admissions: "", outcomes: "", faq: "" },
    hub: MOCK_HUBS[2], isFeatured: false,
    publishedAt: "2026-03-15T10:00:00+02:00", updatedAt: "2026-03-15T10:00:00+02:00", seo: null,
  },
  {
    id: 904, slug: "msc-psychologia-mathisis",
    url: `${WP_BASE_URL}/programs/msc-psychologia-mathisis/`,
    title: "ΜΔΕ Ψυχολογία της Μάθησης",
    excerpt: "Θεωρητικές και πρακτικές προσεγγίσεις στην ψυχολογία της εκπαίδευσης και της μάθησης.",
    contentHtml: "<p>Πλήρης περιγραφή...</p>",
    featuredImage: { id: 204, url: "https://images.unsplash.com/photo-1694230155228-cdde50083573?w=800", alt: "Ψυχολογία Μάθησης", width: 800, height: 600, mimeType: "image/jpeg" },
    summary: { level: "Master", category: "Ψυχολογία", university: "Πάντειο Πανεπιστήμιο", mode: "Υβριδικό", city: "Αθήνα", uniType: "Δημόσιο", tuition: "2500", duration: "18 μήνες", language: "Ελληνικά", deadline: "2026-07-15", format: "Υβριδικό" },
    taxonomies: {
      level: [{ id: 1, name: "Master", slug: "master", url: "" }],
      category: [{ id: 13, name: "Ψυχολογία", slug: "psychology", url: "" }],
      university: [{ id: 14, name: "Πάντειο", slug: "panteion", url: "" }],
      mode: [{ id: 4, name: "Υβριδικό", slug: "hybrid", url: "" }],
      city: [{ id: 5, name: "Αθήνα", slug: "athens", url: "" }],
      uniType: [{ id: 6, name: "Δημόσιο", slug: "public", url: "" }],
    },
    sections: { overview: "", curriculum: "", admissions: "", outcomes: "", faq: "" },
    hub: MOCK_HUBS[2], isFeatured: false,
    publishedAt: "2026-03-20T10:00:00+02:00", updatedAt: "2026-03-20T10:00:00+02:00", seo: null,
  },
  {
    id: 905, slug: "msc-epistimes-agogis",
    url: `${WP_BASE_URL}/programs/msc-epistimes-agogis/`,
    title: "ΜΔΕ Επιστήμες Αγωγής",
    excerpt: "Εμβάθυνση στις θεωρητικές βάσεις της εκπαιδευτικής επιστήμης.",
    contentHtml: "<p>Πλήρης περιγραφή...</p>",
    featuredImage: { id: 205, url: "https://images.unsplash.com/photo-1759317700289-2f4be8f9b1db?w=800", alt: "Επιστήμες Αγωγής", width: 800, height: 600, mimeType: "image/jpeg" },
    summary: { level: "Master", category: "Εκπαίδευση", university: "ΔΠΘ", mode: "Δια Ζώσης", city: "Ξάνθη", uniType: "Δημόσιο", tuition: "1800", duration: "12 μήνες", language: "Ελληνικά", deadline: "2026-08-30", format: "In-person" },
    taxonomies: {
      level: [{ id: 1, name: "Master", slug: "master", url: "" }],
      category: [{ id: 2, name: "Εκπαίδευση", slug: "education", url: "" }],
      university: [{ id: 15, name: "ΔΠΘ", slug: "duth", url: "" }],
      mode: [{ id: 12, name: "Δια Ζώσης", slug: "in-person", url: "" }],
      city: [{ id: 16, name: "Ξάνθη", slug: "xanthi", url: "" }],
      uniType: [{ id: 6, name: "Δημόσιο", slug: "public", url: "" }],
    },
    sections: { overview: "", curriculum: "", admissions: "", outcomes: "", faq: "" },
    hub: MOCK_HUBS[2], isFeatured: false,
    publishedAt: "2026-03-25T10:00:00+02:00", updatedAt: "2026-03-25T10:00:00+02:00", seo: null,
  },
  {
    id: 906, slug: "msc-ekpaideusi-enilikon",
    url: `${WP_BASE_URL}/programs/msc-ekpaideusi-enilikon/`,
    title: "ΜΔΕ Εκπαίδευση Ενηλίκων & Δια Βίου Μάθηση",
    excerpt: "Εξειδίκευση στη δια βίου μάθηση, την εκπαίδευση ενηλίκων και την επαγγελματική κατάρτιση.",
    contentHtml: "<p>Πλήρης περιγραφή...</p>",
    featuredImage: { id: 206, url: "https://images.unsplash.com/photo-1765408217678-545de3e8941d?w=800", alt: "Εκπαίδευση Ενηλίκων", width: 800, height: 600, mimeType: "image/jpeg" },
    summary: { level: "Master", category: "Εκπαίδευση", university: "ΕΑΠ", mode: "Εξ Αποστάσεως", city: "Πάτρα", uniType: "Δημόσιο", tuition: "2200", duration: "24 μήνες", language: "Ελληνικά", deadline: "2026-09-30", format: "Online" },
    taxonomies: {
      level: [{ id: 1, name: "Master", slug: "master", url: "" }],
      category: [{ id: 2, name: "Εκπαίδευση", slug: "education", url: "" }],
      university: [{ id: 17, name: "ΕΑΠ", slug: "eap", url: "" }],
      mode: [{ id: 9, name: "Εξ Αποστάσεως", slug: "online", url: "" }],
      city: [{ id: 18, name: "Πάτρα", slug: "patra", url: "" }],
      uniType: [{ id: 6, name: "Δημόσιο", slug: "public", url: "" }],
    },
    sections: { overview: "", curriculum: "", admissions: "", outcomes: "", faq: "" },
    hub: MOCK_HUBS[2], isFeatured: false,
    publishedAt: "2026-03-28T10:00:00+02:00", updatedAt: "2026-03-28T10:00:00+02:00", seo: null,
  },
];
